### ISSUE TITLE
Theme preview ; suggestion

### ISSUE THREAD

**Issue by mbaneshi** [yazi-rs/themes#4]
Hi there 

Thank you so much, for this amazing tool.

I want to suggest you to put some sort of theme preview in readme.

**Comment by vitormv** [comment]
YES! Would make it so much easier to see whats the difference between each without having to blindly copy files from the repo in order to see how it looks

**Comment by sxyazi** [comment]
Done, see https://github.com/yazi-rs/themes/blob/main/README.md
